FROM python:3.10

WORKDIR /opt/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY requirements.txt requirements.txt

RUN  pip3.10 install --upgrade pip \
     && pip3.10 install -r requirements.txt

COPY . .

ENTRYPOINT ["python3", "main.py"]
