version: '3.5'

services:
  vertica:
    image: jbfavre/vertica:latest
    ports:
      - 5433:5433

  flask:
    build:
      context: flask/
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    depends_on:
      - vertica

  nginx:
    image: nginx:1.25
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/flask.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 5005:80
    depends_on:
      - flask
