services:
  ugc_logstash:
    container_name: ugc_logstash
    image: logstash:8.10.2
    depends_on:
        - ugc_elasticsearch
    environment:
      XPACK_MONITORING_ENABLED: "false"
      ES_HOST: "ugc-elasticsearch:9200"
    ports:
      - "5044:5044/udp"
      - "5045:5045/udp"
    volumes:
      - ./deploy/logstash.conf:/config/logstash.conf:ro
    command: logstash -f /config/logstash.conf

  ugc_elasticsearch:
    container_name: ugc-elasticsearch
    image: elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ports:
      - 9200:9200
    volumes:
      - ./deploy/esdata:/usr/share/elasticsearch/data

  ugc_kibana:
    container_name: ugc_kibana
    image: kibana:8.10.2
    ports:
      - 5601:5601
    depends_on:
      - ugc_elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://ugc-elasticsearch:9200
