version: '3.5'

services:
  postgres:
    image: postgres:15
    container_name: postgres_research
    volumes:
      - postgres_database:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database
    ports:
      - 5432:5432

volumes:
  postgres_database:
